---
title             : "How to use papaja: An Example Manuscript Including Basic Instructions"
shorttitle        : "How to use papaja"

author: 
  - name          : "Frederik Aust"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Department Psychology, University of Cologne, Herbert-Lewin-Str. 2, 50931 Köln, Germany"
    email         : "frederik.aust@uni-koeln.de"
affiliation       :
  - id            : "1"
    institution   : "University of Cologne"

author_note: |
  `papaja` has not yet been submitted to CRAN; a development version is available at https://github.com/crsh/papaja.
abstract: |
  This manuscript demonstrates how to use R Markdown and papaja to
  create an APA conform manuscript. papaja builds on R Markdown, which
  uses pandoc to turn Markdown into PDF or Word documents. The conversion
  to Word documents currently supports only a limited set of features.
  
keywords: "APA style, knitr, R, R markdown, papaja"
wordcount: "Too lazy to count"

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
linkcolor         : "blue"
mask              : no
draft             : no

classoption       : "man"
output            : papaja::apa6_docx # Use papaja::apa6_docx for Word documents
---

```{r child = 'Setup.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Introduction --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Introduction.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Materials and methods --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Mat_Met.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Results --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Results.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Discussion --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Discussion.Rmd'}
```


<!-- `r if (!knitr:::is_latex_output()) '# References {-}'` -->
# References
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

