---
title: "Test_word_output"
author: "Bob"
date: "7 novembre 2018"
output: 
  word_document:
    reference_docx: mystyles_number.docx
---

```{r child = 'Setup.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Introduction --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Introduction.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Materials and methods --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Mat_Met.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Results --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Results.Rmd'}
```

<!----------------------------------------------------------------------------->
<!-- Discussion --> 
<!-----------------------------------------------------------------------------> 
```{r child = 'Discussion.Rmd'}
```


<!-- `r if (!knitr:::is_latex_output()) '# References {-}'` -->
# References
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}